docker-compose.yml
lib/homes_england/domain/project.rb
lib/homes_england/gateway/file_project.rb
lib/homes_england/namespaces.rb
lib/homes_england/use_case/create_new_project.rb
lib/homes_england/use_cases.rb
lib/loader.rb
lib/use_case_factory.rb
spec/acceptance/homes_england/create_new_hif_project_spec.rb
spec/spec_helper.rb
spec/unit/homes_england/gateway/file_project_spec.rb
spec/unit/homes_england/use_case/create_new_project_spec.rb

Creates a new project using a flat file to store the data, this will change in the future

Add create new project usecase

---

lib/delivery_mechanism/web_routes.rb
lib/homes_england/use_case/find_project.rb
lib/homes_england/use_cases.rb
spec/acceptance/homes_england/get_hif_project_spec.rb
spec/unit/homes_england/use_case/find_project_spec.rb
spec/web_routes/finding_project_spec.rb

GET : /project/find with id param will find Project
Added FindProject use case

GET Project by Id

---

lib/delivery_mechanism/web_routes.rb
lib/homes_england/gateway/file_project.rb
lib/homes_england/use_case/update_project.rb
lib/homes_england/use_cases.rb
spec/acceptance/homes_england/update_project_spec.rb
spec/unit/homes_england/use_case/update_project_spec.rb
spec/web_routes/finding_project_spec.rb
spec/web_routes/update_project_spec.rb

Posting to /project/update will update the project via the gateway. Currently posting with json:
`id: <id>,
project: {
type: <type>,
baselineData: <data>
}`
Will return a `404` if `id` is not found or `project`/`id` is `nil`. (Will add additional checks once we have worked out the validation.)

POST Update Project

---

lib/delivery_mechanism/web_routes.rb

WHY - We're leaving lots of connections open

Disconnect from database when request is finished

---

lib/delivery_mechanism/web_routes.rb
spec/web_routes/get_base_return_spec.rb

Added /project/:id/return - runs get base return use case

Added get base return webroute

---

lib/delivery_mechanism/web_routes.rb
lib/local_authority/gateway/gov_email_notification_gateway.rb
lib/local_authority/use_case/send_notification.rb
spec/unit/local_authority/gateway/gov_email_notification_gateway_spec.rb
spec/unit/local_authority/use_case/send_notification_spec.rb
spec/web_routes/create_new_project_spec.rb
spec/web_routes/get_base_return_spec.rb
spec/web_routes/request_access_token_spec.rb

send notifications are sent token so url can be created correctly

/token/request calls create token usecase

---

README.md

Readme says that application port is 3000, but currently its 4567.

Fix port information in readme

---

bin/run_tests.sh
db/migrations/6_add_users.rb
lib/database_administrator/postgres.rb
lib/homes_england/use_case/add_user.rb
lib/homes_england/use_cases.rb
lib/local_authority/domain/user.rb
lib/local_authority/gateway/sequel_email_whitelist_gateway.rb
lib/local_authority/gateway/sequel_users.rb
lib/local_authority/use_case/check_email.rb
lib/local_authority/use_case/create_access_token.rb
lib/local_authority/use_cases.rb
spec/acceptance/local_authority/authorise_user_spec.rb
spec/acceptance/local_authority/authorise_user_with_project_spec.rb
spec/database_context.rb
spec/unit/homes_england/use_case/add_user_spec.rb
spec/unit/local_authority/gateway/sequel_email_whitelist_gateway_spec.rb
spec/unit/local_authority/gateway/sequel_users_spec.rb
spec/unit/local_authority/use_case/check_email_spec.rb
spec/web_routes/request_access_token_spec.rb

Also includes acceptance tests for unimplemented per-project authentication.

Use database and store project ids

---

lib/delivery_mechanism/web_routes.rb
lib/local_authority/use_case/check_api_key.rb
spec/web_routes/create_return_spec.rb

What - Fixes authentication per project via the webroutes

Pass project_ids to check_email use case in webroutes

---

lib/delivery_mechanism/controllers/post_project_to_users.rb
lib/delivery_mechanism/web_routes.rb
spec/web_routes/add_users_to_project_spec.rb

Add users to project

---

lib/homes_england/gateway/in_memory_template.rb
lib/local_authority/gateway/in_memory_return_template.rb
spec/acceptance/local_authority/perform_return_spec.rb
spec/fixtures/base_return.json
spec/fixtures/second_base_return.json

What
Moved boolean values to a "Yes" "No" enum
Why 
Dependencies do not work with boolean values.

Moved booleans to Yes No enums

---

lib/local_authority/use_case/send_notification.rb

Refactor send notification

---

lib/local_authority/namespaces.rb
lib/local_authority/refinement/deep_copy.rb
lib/local_authority/refinement/hash_deep_merge.rb
lib/local_authority/use_case/calculate_hif_return.rb
spec/unit/local_authority/use_case/calculate_hif_return_spec.rb

Refactor calculate hif return

---

lib/local_authority/use_case/populate_return_template.rb
spec/unit/local_authority/use_case/populate_return_template_spec.rb

What - Fixes the issues copying data to multiple dependencies in return populator

Multiple dependencies

---

lib/homes_england/gateway/in_memory_template.rb
lib/local_authority/gateway/in_memory_return_template.rb
spec/acceptance/local_authority/perform_return_spec.rb
spec/fixtures/base_return.json
spec/fixtures/hif_baseline.json
spec/fixtures/second_base_return.json

WHAT 
- Updates the baseline to allow for easier creation of the baseline editor in future
- Update the financials section to make it more clear to use

Update baseline & return schema

---

lib/homes_england/builder/template/templates/hif_template.rb

Add titles to baseline template to allow the frontend baseline viewer to display things more clearly

Add titles to baseline

---

lib/homes_england/builder/template/templates/hif_template.rb
lib/local_authority/gateway/in_memory_return_template.rb

WHY:
Schema did not match the data

Update granted to grantedReference

---

lib/common/namespaces.rb
lib/common/refinement/hash_has_path.rb
lib/common/use_case/get_template_path_titles.rb
lib/common/use_cases.rb
lib/delivery_mechanism/web_routes.rb
lib/dependency_factory.rb
lib/homes_england/domain/template.rb
lib/homes_england/use_case/validate_project.rb
lib/homes_england/use_cases.rb
lib/local_authority/use_case/get_return_template_path_types.rb
lib/local_authority/use_case/validate_return.rb
lib/local_authority/use_cases.rb
spec/acceptance/homes_england/validate_project_spec.rb
spec/fixtures/hif_baseline_missing.json
spec/unit/common/get_template_path_titles_spec.rb
spec/unit/homes_england/use_case/validate_project_spec.rb
spec/unit/local_authority/use_case/validate_return_spec.rb
spec/web_routes/validate_project_spec.rb

Created Use Case, added a webroute.
Also moved use case for getting path titles to common as this was needed for both validating returns and projects.

Create use case for validating new project data.

---

lib/local_authority/gateway/in_memory_return_template.rb
spec/fixtures/base_return.json
spec/fixtures/second_base_return.json

**WHAT**
- Marks a field as extended text
- Adds total HIF Grant to schema
- Changes title of funding profiles tab

Update Return Schema based on feedback

---

db/migrations/9_merge_funding_package_sections.rb
lib/local_authority/gateway/in_memory_return_template.rb
spec/fixtures/base_return.json
spec/fixtures/second_base_return.json
spec/unit/database_administrator/migration_9_spec.rb

Merge hif spend section with funding stack

---

lib/homes_england/builder/template/templates/hif_template.rb
lib/homes_england/gateway/sequel_project.rb
lib/homes_england/use_case/create_new_project.rb
lib/homes_england/use_case/submit_project.rb
lib/homes_england/use_case/update_project.rb
spec/acceptance/homes_england/submit_project_spec.rb
spec/acceptance/homes_england/update_project_spec.rb
spec/unit/homes_england/gateway/sequel_project_spec.rb
spec/unit/homes_england/use_case/submit_project_spec.rb
spec/unit/homes_england/use_case/update_project_spec.rb

Adds a new state to projects of LA Draft.
Flow should now be:
- A new empty baseline is added: Status = Draft
- HE user adds information to the empty baseline and submits: Status = LA Draft
- LA user adds information to the partially filled baseline and submits: Status = Submitted

Baseline Editor state

---

.circleci/config.yml
Gemfile
Gemfile.lock
spec/spec_helper.rb

Code coverage

---

lib/local_authority/gateway/in_memory_return_template.rb
spec/acceptance/local_authority/perform_return_spec.rb
spec/fixtures/base_return.json
spec/fixtures/second_base_return.json
spec/unit/local_authority/gateway/in_memory_return_template_spec.rb

Adds the following tabs when environment variables are enabled:
- Outputs - Actuals
- s151 Claim
- Submission
- RM Monthly Catchup

Add tabs from spreadsheet to return Schema

---

lib/local_authority/gateway/in_memory_return_template.rb

Renamed to s151 to be consistent with other references.

Rename S.151 tab to match existing references to s151

---

lib/homes_england/builder/template/templates/ac_template.rb

Corrected some invalid array elements of the schema and updated some ordering/titles to match baseline data.

Correct AC baseline editor schema

---

lib/homes_england/builder/template/templates/ac_template.rb

Add some missing fields/ move some fields based on the source spreadsheet

AC baseline improvements

---

lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/schemas/ac_project.json

Resolves conflict between new ui convertor and ac projects

Add ac project template to ui generator

---

lib/ui/gateway/schemas/hif_project.json
lib/ui/use_case/convert_core_hif_project.rb
lib/ui/use_case/convert_ui_hif_project.rb
lib/ui/use_case/validate_project.rb
spec/acceptance/homes_england/validate_project_spec.rb
spec/acceptance/ui/hif_validate_project_spec.rb
spec/fixtures/hif_baseline_missing_core.json
spec/fixtures/hif_baseline_missing_ui.json

Restructure Infrastructues Tab

---

lib/ui/gateway/schemas/hif_project.json
lib/ui/use_case/convert_core_hif_project.rb
lib/ui/use_case/convert_ui_hif_project.rb
spec/fixtures/hif_baseline_ui.json
spec/fixtures/hif_empty_baseline_ui.json

Edit ui schema to put funding profiles on one page.

---

lib/ui/gateway/schemas/hif_project.json

Marking fields with longish text as text areas for the baseline editor schema.

Add text areas where appropriate

---

lib/homes_england/builder/template/templates/ac_template.rb
lib/ui/gateway/schemas/ac_project.json

Doesn't look perfect but everything is in the right order now.

Make some schema changes

---

lib/ui/gateway/schemas/ac_project.json

Change financials tab to match feedback

---

lib/ui/gateway/schemas/ac_project.json

Change milestones tab to match feedback

---

lib/ui/gateway/schemas/ac_project.json

Change Outputs tab schema based on UAT feedback

---

lib/ui/gateway/schemas/ac_project.json

Change mmc to table

---

lib/ui/gateway/schemas/ac_project.json

Change around dates in milestones

---

lib/ui/gateway/schemas/ac_project.json

- Changed 'Site' to 'Site Name'
- Made the array just encompass the site and amount
- Make these side buy side

Funding naming changes

---

lib/ui/gateway/schemas/ac_project.json

Display the funding drawdown as quarterly

---

lib/ui/gateway/schemas/ac_project.json

(I also added a stray missing currency field in here )

Mark the maximum number of digits on some fields

---

lib/local_authority/gateway/in_memory_return_template.rb

Language used seems slightly different to Trello card so please double check

Only show amendment confirmation if HIF request has changed

---

lib/ui/use_case/convert_core_hif_project.rb
lib/ui/use_case/convert_ui_hif_project.rb
spec/acceptance/ui/hif_returns_spec.rb
spec/fixtures/base_return.json
spec/fixtures/hif_baseline_core.json
spec/fixtures/hif_baseline_ui.json
spec/fixtures/hif_saved_base_return.json
spec/fixtures/hif_updated_return.json
spec/fixtures/second_base_return.json

Moved the compact inside the map and put some catches in to catch arrays of nils.

Fix error on converting project.

---

Gemfile
Gemfile.lock
Makefile

Add linter

---

lib/local_authority/gateway/ac_returns_schema.rb
lib/ui/gateway/in_memory_return_schema.rb
lib/ui/gateway/schemas/ac_return.json

- Delete un needed tabs as opposed to setting them to nil.
- Add the json schema for AC returns to validate against.

Fix some errors in JSON validation

---

lib/ui/use_case/get_schema_for_return.rb
spec/unit/ui/use_case/get_schema_for_returns_spec.rb

(I forgot to add these files to the previous pull request)

Add get schema for returns ui use case

---

lib/local_authority/gateway/ac_returns_schema.rb
lib/ui/gateway/schemas/ac_return.json

Make schema changes for ac returns

---

lib/ui/gateway/schemas/ac_project.json
lib/ui/gateway/schemas/ac_return.json

For https://github.com/homes-england/monitor-frontend/pull/181

Mark conditions as numbered

---

lib/ui/gateway/schemas/ac_project.json

Removes the currency marker from fields which aren't money

Remove currency marking from the units fields

---

lib/ui/gateway/schemas/ac_project.json

Remove maximum field

---

lib/ui/gateway/schemas/ac_project.json
lib/ui/gateway/schemas/ac_return.json

Also use the more generic functions in https://github.com/homes-england/monitor-frontend/pull/194

Add calculations for projectValue

---

lib/local_authority/gateway/hif_returns_schema.rb

Correcting the source key for the hidden current funding fields

Change source key for current funding

---

lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/acceptance/ui/hif_returns_spec.rb
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/hif_updated_return_ui.json

Rearrange how the outputs screen looks

---

docker-compose.yml
lib/ui/gateway/schemas/hif_return.json

Linked to PR https://github.com/homes-england/monitor-frontend/pull/224

Remove unecessary hidden tags from infras > planning tabs

---

lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/hif_updated_return_ui.json

- Variance from total hif grant
- variance from end date
- variance from project longstop date

S151 confirmation variances

---

lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb

https://sentry.io/homes-england/monitor-api/issues/813099698/events/39891857452/  
https://sentry.io/homes-england/monitor-api/issues/813062068/events/39890261704/

Fix additional risks conversion crashes

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json

Procurement variance and dependencies

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json

Make statutory consents independent of section 106 status

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/fixtures/base_return.json
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/hif_updated_return_ui.json
spec/fixtures/second_base_return.json

- Added description of infrastructure
- Added variance calculations to total cost and hif spend section
- Added some missing fields

Funding packages adjustments

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/hif_updated_return_ui.json

- Add some missing fields
- add some variances

Edit public and private sections

---

lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb

- fits procurement into variance component

Change titles and rearrange procurement

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/acceptance/local_authority/perform_return_spec.rb
spec/fixtures/base_return.json
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/hif_updated_return_ui.json
spec/fixtures/second_base_return.json

- option to switch between fully and partially funded 
- funding calculations based on previous return

More funding packages changes 

---

docker-compose.yml
lib/homes_england/builder/template/templates/hif_template.rb
lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/in_memory_return_schema.rb
lib/ui/gateway/schemas/hif_project.json
lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_project.rb
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_project.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/acceptance/local_authority/perform_return_spec.rb
spec/fixtures/base_return.json
spec/fixtures/hif_baseline_core.json
spec/fixtures/hif_baseline_ui.json
spec/fixtures/second_base_return.json
spec/unit/local_authority/gateway/hif_returns_schema_spec.rb
spec/unit/ui/gateway/in_memory_return_schema_spec.rb

New recovery tab on baseline:
New recovery tab on returns:

Hif recovery tab

---

lib/ui/gateway/schemas/hif_return.json

As per card:
https://trello.com/c/gMS1tC4o/104-s151-return-claim-title-of-evidence-of-next-quarter-spend-needs-changing-to-breakdown-of-next-quarter-spend-need-to-add-help-tex

Update title of breakdownOfNextQuarterSpend section

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json
spec/acceptance/local_authority/perform_return_spec.rb
spec/fixtures/base_return.json
spec/fixtures/hif_baseline_core.json
spec/fixtures/hif_baseline_ui.json
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/second_base_return.json

Based on comment here: https://trello.com/c/dTej9Rso/100-recovery-there-is-no-tab-for-recovery-is-that-because-this-project-is-not-expected-to-recover

Adjustments to HIF Recovery tab

---

lib/common/domain/template.rb
lib/ui/gateway/schemas/hif_project.json
lib/ui/use_case/validate_project.rb
spec/fixtures/hif_baseline_missing_ui.json
spec/unit/homes_england/use_case/validate_project_spec.rb
spec/unit/ui/use_case/validate_project_spec.rb

- Removes nulls from data before validating.
- Adds required markers on parent objects if they have a child which is required
- separates objects at the same level into different error paths

Fix validation issues

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json

Compliments https://github.com/homes-england/monitor-frontend/pull/260

Carry forward incomplete progress actions

---

lib/ui/gateway/schemas/hif_return.json

Last pull changed the wrong schema

Change 'Evidence of Spend for the Past Quarter' to 'Evidence to Support Forecast Spend for Next Quarter'

---

db/migrations/14_rename_infrastructures_delivery.rb
lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/fixtures/base_return.json
spec/fixtures/hif_return_core.json
spec/fixtures/second_base_return.json
spec/unit/database_administrator/migration_12_spec.rb
spec/unit/ui/use_case/convert_ui_return_spec.rb

infrastructureDelivery had the same path on both HIF and AC but had different types, this resolves that conflict for BI & the export endpoint.

Move HIF's infrastructureDelivery to infrastructureDeliveries

---

lib/ui/gateway/schemas/ac_return.json

Add year options up to 2039/40

---

lib/homes_england/builder/template/templates/ac_template.rb
lib/ui/gateway/schemas/ac_project.json
spec/fixtures/ac_baseline_core.json
spec/fixtures/ac_baseline_ui.json

Add receipt fields to baseline

---

lib/local_authority/gateway/ac_returns_schema.rb
lib/ui/gateway/schemas/ac_return.json
spec/fixtures/ac_return_core.json
spec/fixtures/ac_return_ui.json

Add authorisation field on review tab

---

lib/delivery_mechanism/controllers/post_request_token.rb
lib/delivery_mechanism/controllers/post_submit_return.rb
lib/delivery_mechanism/web_routes.rb
lib/local_authority/domain/access_token.rb
lib/local_authority/use_case/check_api_key.rb
lib/local_authority/use_case/check_email.rb
lib/local_authority/use_case/create_access_token.rb
lib/local_authority/use_case/create_api_key.rb
lib/local_authority/use_case/expend_access_token.rb
lib/local_authority/use_case/get_user_projects.rb
lib/local_authority/use_cases.rb
spec/acceptance/local_authority/authorise_user_with_project_spec.rb
spec/unit/local_authority/use_case/check_api_key_spec.rb
spec/unit/local_authority/use_case/check_email_spec.rb
spec/unit/local_authority/use_case/create_access_token_spec.rb
spec/unit/local_authority/use_case/create_api_key_spec.rb
spec/unit/local_authority/use_case/expend_access_token_spec.rb
spec/unit/local_authority/use_case/get_user_project_spec.rb
spec/web_routes/expend_access_token_spec.rb
spec/web_routes/get_users_projects_spec.rb
spec/web_routes/request_access_token_spec.rb
spec/web_routes/validate_project_spec.rb
spec/web_routes/validate_return_spec.rb

Linked to https://github.com/homes-england/monitor-frontend/pull/282
This also switches the tokens to just check for users, not users linked to projects.

Create webroute for project list

---

lib/local_authority/gateway/ac_returns_schema.rb
lib/ui/gateway/schemas/ac_return.json
spec/fixtures/ac_return_core.json
spec/fixtures/ac_return_ui.json

Add signature upload for s151 submission confirmation

---

lib/local_authority/gateway/ac_returns_schema.rb
lib/ui/gateway/schemas/ac_return.json
spec/fixtures/ac_return_core.json
spec/fixtures/ac_return_ui.json

Add upload field for evidence relating to required changes

---

lib/delivery_mechanism/web_routes.rb
lib/ui/gateway/blank_projects/ac.json
lib/ui/gateway/blank_projects/mvf.json
lib/ui/gateway/in_memory_new_project.rb
lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/in_memory_return_schema.rb
lib/ui/gateways.rb
lib/ui/use_case/create_project.rb
lib/ui/use_cases.rb
spec/acceptance/homes_england/validate_project_spec.rb
spec/acceptance/local_authority/perform_return_spec.rb
spec/acceptance/local_authority/validate_return_spec.rb
spec/acceptance/ui/hif_project_spec.rb
spec/acceptance/ui/hif_returns_spec.rb
spec/acceptance/ui/hif_validate_project_spec.rb
spec/acceptance/ui/hif_validate_return_spec.rb
spec/unit/ui/gateway/in_memory_new_project_spec.rb
spec/unit/ui/use_case/convert_core_ac_project_spec.rb
spec/unit/ui/use_case/convert_core_ac_return_spec.rb
spec/unit/ui/use_case/convert_core_hif_project_spec.rb
spec/unit/ui/use_case/convert_core_hif_return_spec.rb
spec/unit/ui/use_case/convert_ui_ac_project_spec.rb
spec/unit/ui/use_case/convert_ui_ac_return_spec.rb
spec/unit/ui/use_case/convert_ui_hif_project_spec.rb
spec/unit/ui/use_case/convert_ui_hif_return_spec.rb
spec/unit/ui/use_case/create_project_spec.rb
spec/web_routes/add_users_to_project_spec.rb
spec/web_routes/create_new_project_spec.rb

I've had to add different webroutes for the admin access so we can still add projects and people like we did before, but with a different url. But if any ideas how to do it with the same webroute, that would be good to know.

Adapt to allow project creation and adding users to projects

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/ac_project.json
lib/ui/gateway/schemas/hif_return.json
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json

linked: https://github.com/homes-england/monitor-frontend/pull/292

Add calculations to outputs forecast to pull from outputs actuals

---

lib/delivery_mechanism/controllers/get_base_claim.rb
lib/ui/gateway/schemas/claims/hif.json
lib/ui/use_case/get_base_claim.rb
lib/ui/use_cases.rb
spec/unit/ui/use_case/get_base_claim_spec.rb
spec/web_routes/get_base_claim_spec.rb

This is just sending the schema across so that we can create new claims - not yet implementing source keys.

Get base claim use case

---

lib/homes_england/builder/template/templates/ff_template.json
lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/schemas/ff/project/grant_expenditure.json
lib/ui/use_case/convert_core_ff_project.rb
lib/ui/use_case/convert_ui_ff_project.rb
spec/unit/ui/gateway/in_memory_project_schema_spec.rb

Add HIF Grant Expenditure tab to Forward Funding

---

lib/homes_england/builder/template/templates/ff_template.json
lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/schemas/ff/project/risks.json
lib/ui/use_case/convert_core_ff_project.rb
lib/ui/use_case/convert_ui_ff_project.rb
spec/unit/ui/gateway/in_memory_project_schema_spec.rb

Add risks tab to forward funding baseline

---

lib/homes_england/builder/template/templates/ff_template.json
lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/schemas/ff/project/hif_recovery.json
lib/ui/use_case/convert_core_ff_project.rb
lib/ui/use_case/convert_ui_ff_project.rb
spec/unit/ui/gateway/in_memory_project_schema_spec.rb

Add hif recovery tab to forward funding

---

lib/homes_england/builder/template/templates/ff_template.json
lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/schemas/ff/project/wider_scheme.json
lib/ui/use_case/convert_core_ff_project.rb
lib/ui/use_case/convert_ui_ff_project.rb
spec/unit/ui/gateway/in_memory_project_schema_spec.rb

Add wider scheme tab to forward funding

---

lib/homes_england/builder/template/templates/ff_template.json
lib/local_authority/use_case/get_infrastructures.rb
lib/ui/gateway/schemas/ff/project/infrastructures.json
lib/ui/gateway/schemas/ff/project/milestones.json
spec/acceptance/homes_england/get_infrastructures_spec.rb
spec/unit/local_authority/use_case/get_infrastructures_spec.rb

Also includes adding an ID and type to the infrastructures in the get infrastructures use case.

Add schema for infrastructures tab 

---

docker-compose.yml
lib/ui/gateway/blank_projects/ff.json
lib/ui/gateway/in_memory_new_project.rb
spec/unit/ui/gateway/in_memory_new_project_spec.rb

Add blank ff project template to create from front-end.
Requires https://github.com/homes-england/monitor-frontend/pull/308

Add ff funding to project create

---

lib/delivery_mechanism/controllers/amend_baseline.rb
lib/delivery_mechanism/controllers/get_baselines.rb
lib/delivery_mechanism/controllers/submit_baseline.rb
lib/homes_england/use_case/amend_baseline.rb
lib/ui/use_case/amend_baseline.rb
lib/ui/use_case/get_baselines.rb
lib/ui/use_cases.rb
spec/unit/homes_england/use_case/amend_baseline_spec.rb
spec/unit/ui/get_baselines_spec.rb
spec/unit/ui/use_case/amend_baseline_spec.rb
spec/web_routes/amend_baseline_spec.rb
spec/web_routes/get_baselines_spec.rb
spec/web_routes/submit_baseline_spec.rb

- amend baseline webroute 
- submit baseline webroute
- get baselines webroute

Webroutes for editting baseline

---

lib/ui/use_case/convert_core_hif_project.rb
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_core_project.rb
lib/ui/use_case/convert_core_return.rb
lib/ui/use_case/convert_ui_hif_project.rb
lib/ui/use_case/convert_ui_hif_return.rb
lib/ui/use_case/convert_ui_project.rb
lib/ui/use_case/convert_ui_return.rb
spec/acceptance/ui/hif_returns_spec.rb
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/hif_updated_return_ui.json
spec/unit/local_authority/use_case/get_base_claim_spec.rb
spec/unit/local_authority/use_case/pcs_populate_claim_spec.rb
spec/unit/ui/use_case/convert_core_ac_project_spec.rb
spec/unit/ui/use_case/convert_core_ac_return_spec.rb
spec/unit/ui/use_case/convert_core_hif_project_spec.rb
spec/unit/ui/use_case/convert_core_hif_return_spec.rb
spec/unit/ui/use_case/convert_core_project_spec.rb
spec/unit/ui/use_case/convert_core_return_spec.rb
spec/unit/ui/use_case/convert_ui_ac_project_spec.rb
spec/unit/ui/use_case/convert_ui_ac_return_spec.rb
spec/unit/ui/use_case/convert_ui_hif_project_spec.rb
spec/unit/ui/use_case/convert_ui_hif_return_spec.rb
spec/unit/ui/use_case/convert_ui_project_spec.rb
spec/unit/ui/use_case/convert_ui_return_spec.rb

- check for value being nil before trying to map it. 
- compact data after conversion to remove nil values

Prevent errors in data

---

lib/ui/gateway/schemas/hif_project.json

Requires https://github.com/homes-england/monitor-frontend/pull/316

Make milestones only adjustable by Homes England

---

lib/ui/gateway/schemas/hif_project.json

- section 151, statutory consents and section 106 are now all LA readonly only

Edit some access rights

---

db/migrations/22_move_rm_links_to_arrays.rb
lib/homes_england/builder/template/templates/hif_template.rb
lib/ui/gateway/schemas/hif_project.json
spec/fixtures/hif_baseline_core.json
spec/fixtures/hif_baseline_ui.json
spec/unit/database_administrator/migration_22_spec.rb

add multiple PCS references
select more than one type of MHCLG programmes 
select more than one type of OGB programmes
select more than one type of Other Government Departments interested 
select more than one type of housing policy areas

Ability to add multiple option rm

---

lib/common/preprocess_JSON.rb
lib/ui/gateway/in_memory_project_schema.rb
lib/ui/gateway/in_memory_return_schema.rb
lib/ui/gateway/schemas/ac_project.json
lib/ui/gateway/schemas/hif_return.json
spec/unit/common/preprocess_JSON_spec.rb

What - Adds preprocessing to allow for newlines in schema JSONs  
Why - Calculations quickly become unwieldy, newlines would go a long way towards improving this issue

Calculation readability

---

lib/ui/gateway/schemas/hif_return.json

This is a repeat of https://github.com/homes-england/monitor-api/pull/492/files . As somehow it is no longer in the code.

Display N/A if no funding desc.

---

lib/ui/gateway/schemas/hif_return.json

https://trello.com/c/s8RRnEwf/209-text-to-be-removed-description-of-live-action

Remove calculated text

---

lib/ui/gateway/schemas/hif_return.json

Requires https://github.com/homes-england/monitor-frontend/pull/347

Hide amount secured when funding is 0

---

lib/local_authority/gateway/hif_returns_schema.rb
lib/ui/gateway/schemas/ac_project.json
lib/ui/gateway/schemas/hif_project.json
lib/ui/gateway/schemas/hif_return.json
lib/ui/use_case/convert_core_hif_return.rb
lib/ui/use_case/convert_ui_hif_return.rb
spec/acceptance/homes_england/laac_spec.rb
spec/acceptance/ui/hif_validate_return_spec.rb
spec/acceptance/ui/validate_return_spec.rb
spec/fixtures/ac_valid_ui_baseline_data.json
spec/fixtures/base_return.json
spec/fixtures/hif_mvf_valid_ui_return.json
spec/fixtures/hif_return_core.json
spec/fixtures/hif_return_ui.json
spec/fixtures/hif_return_ui_after_calcs.json
spec/fixtures/hif_saved_base_return_ui.json
spec/fixtures/second_base_return.json

Temporary work silo until staging can be modified again

Pre-master

---

lib/delivery_mechanism/controllers/project_overview.rb
lib/homes_england/use_case/find_project.rb
lib/homes_england/use_case/get_project_overview.rb
lib/homes_england/use_cases.rb
spec/acceptance/homes_england/project_overview_spec.rb
spec/unit/homes_england/use_case/get_project_overview_spec.rb
spec/web_routes/project_overview_spec.rb

To be wired up to a controller in a subsequent PR

Create project overview use case

---

lib/ui/gateway/schemas/ac_project.json

This enables the validation to show each section rather than a number of blank sections

Add titles to AC milestone sections

---

spec/acceptance/local_authority/update_user_role_spec.rb

Co-authored-by: Robert McHugh <robert@madetech.com>

Refactor update user role acceptance test

---

spec/acceptance/ui/hif_claims_spec.rb
spec/fixtures/hif_updated_claim_ui.json

Co-authored-by: Robert McHugh <robert@madetech.com>

Refactor UI HIF claims acceptance test

---

spec/acceptance/ui/hif_project_spec.rb

Co-authored-by: Robert McHugh <robert@madetech.com>

Refactor UI HIF project acceptance test

---

lib/delivery_mechanism/controllers/get_base_return.rb
lib/delivery_mechanism/controllers/get_project_export.rb
lib/delivery_mechanism/controllers/get_project_schema.rb
lib/delivery_mechanism/controllers/get_projects_export.rb
lib/delivery_mechanism/controllers/get_return.rb
lib/delivery_mechanism/controllers/get_returns.rb
lib/delivery_mechanism/controllers/post_expend_token.rb
lib/delivery_mechanism/controllers/submit_project.rb
lib/delivery_mechanism/controllers/unsubmit_project.rb
lib/delivery_mechanism/web_routes.rb

Moved some web routes into individual controllers to make future changes easier.

Move web routes to controllers

---

spec/acceptance/ui/hif_returns_spec.rb

Co-authored-by: Robert McHugh <robert@madetech.com>

Refactor UI HIF returns acceptance test

---

lib/ui/gateway/schemas/hif_return.json

Mark S106 Description as extended text
