homes-england/monitor-api

lib/common/deep_symbolize_keys.rb, lib/delivery_mechanism/web_routes.rb, lib/homes_england/gateway/file_project.rb, spec/web_routes/create_new_project_spec.rb, spec/web_routes/delivery_mechanism_spec_helper.rb
Adds an endpoint for creating a new project with type & baseline data
This does no modification of the data, just passes it all through
=> Endpoint for creating a new project

lib/common/deep_camelize_keys.rb, lib/common/deep_symbolize_keys.rb, lib/common/namespaces.rb, lib/delivery_mechanism/web_routes.rb, lib/homes_england/domain/template.rb, lib/homes_england/gateway/in_memory_template.rb, lib/homes_england/use_case/create_new_project.rb, lib/homes_england/use_case/populate_template.rb, lib/homes_england/use_cases.rb, spec/acceptance/homes_england/create_new_hif_project_spec.rb, spec/acceptance/homes_england/get_hif_project_spec.rb, spec/acceptance/homes_england/update_project_spec.rb, spec/unit/homes_england/gateway/in_memory_template_spec.rb, spec/unit/homes_england/use_case/create_new_project_spec.rb, spec/unit/homes_england/use_case/populate_template_spec.rb, spec/web_routes/finding_project_spec.rb
**WHAT**
Create project populates template data with baseline data.
Added populate template use case which will create a Project data structure by merging baseline data with template data.
Cleaned up some tests whilst logic was added.
**WHY**
Previously the create project cloned the baseline data. We need the baseline data to populate an existing template.
=> Create project POST checks baseline data against existing template.

lib/delivery_mechanism/web_routes.rb, lib/local_authority/use_case/get_returns.rb, lib/local_authority/use_cases.rb, spec/acceptance/local_authority/get_returns_spec.rb, spec/unit/local_authority/use_case/get_returns_spec.rb, spec/web_routes/get_returns_spec.rb
Also addresses some mild errors in my last pull
=> GetReturns can now be accessed via /project/:id/returns

lib/homes_england/gateway/in_memory_template.rb
WHAT - Changes the projectSummary key in the project schema to summary
WHY 
- Redundant naming
- Frontend will soon depend on a "Summary" key existing
=> Change projectSummary to summary

Makefile, docker-compose.yml, lib/local_authority/gateway/gov_email_notification_gateway.rb, spec/unit/local_authority/gateway/gov_email_notification_gateway_spec.rb
WHAT
- Simulates gov notify on local dev
- Puts the token url in the console rather than sending emails
WHY
- Testing locally was painful and would require emails to be sent via gov notify
- We would expend our email allowance, and not be able to run it locally
=> Add gov notify simulator

lib/local_authority/gateway/in_memory_return_template.rb, lib/local_authority/use_case/create_return.rb, lib/local_authority/use_case/find_path_data.rb, lib/local_authority/use_case/get_base_return.rb, lib/local_authority/use_case/get_schema_copy_paths.rb, lib/local_authority/use_case/populate_return_template.rb, lib/local_authority/use_cases.rb, spec/acceptance/local_authority/perform_return_spec.rb, spec/unit/local_authority/use_case/find_path_data_spec.rb, spec/unit/local_authority/use_case/get_base_return_spec.rb, spec/unit/local_authority/use_case/get_schema_copy_paths_spec.rb, spec/unit/local_authority/use_case/populate_return_template_spec.rb
What - Return schemas can now reference a path in the previous returns. The schema path format has changed slightly, it must now be prefixed with the data source for example `[:baseline_data, :cats]` vs `[:return_data, :dogs]` the schema key used to store this path has also changed from `:baselineKey` to `:sourceKey`. Note that there is not currently any way of referencing a specific return.  
Why - This is so that returns using relevant and up to date data can be created.
=> Returns from returns

lib/delivery_mechanism/controllers/post_project_to_users.rb, lib/delivery_mechanism/web_routes.rb, spec/web_routes/add_users_to_project_spec.rb
This PR adds a post route to add multiple users to a project. Such a route is protected behind admin api key that should be hidden within environment variables
=> Add /project/:id/add_users route

lib/local_authority/gateway/in_memory_return_template.rb, spec/acceptance/local_authority/perform_return_spec.rb, spec/fixtures/base_return.json, spec/fixtures/second_base_return.json
WHAT - Adds alternative values to dependencies in enums
WHY - Without these the schema is marked as invalid
=> Update schema dependencies to be valid

lib/local_authority/gateway/in_memory_return_template.rb, spec/fixtures/base_return.json, spec/fixtures/second_base_return.json
WHAT
- Marks fields as variance fields for the frontend to consume
WHY
- To allow us to use the [variance component](https://github.com/homes-england/monitor-frontend/pull/58 ) in the frontend
=> Mark fields as variance fields

lib/local_authority/gateway/in_memory_return_template.rb
WHAT/WHY
A marker in the backend to signal when the UI schema should be using the RiskField component.
=> Add risk: true property to json schema

lib/homes_england/use_case/add_user.rb, lib/local_authority/use_case/check_email.rb, spec/unit/homes_england/use_case/add_user_spec.rb, spec/unit/local_authority/use_case/check_email_spec.rb
WHAT
converts email strings to lowercase 
WHY 
currently email addresses are not being because because the case is mixed
=> Check email string

lib/delivery_mechanism/web_routes.rb, spec/web_routes/get_return_spec.rb
What
- Updates the return get endpoint to use the returnId parameter
WHY
- Guarding requires the ID parameter for validation
**To follow this pull request**
- We need to review our endpoints and update them for consistency and/or sensible interfaces, currently there is a mixture
=> Update get return to allow for guarding

.circleci/config.yml, bin/run_tests.sh, lib/common/namespaces.rb, lib/common/proxy/logging.rb, lib/delivery_mechanism/web_routes.rb, lib/dependencies.rb, lib/dependency_factory.rb, lib/homes_england/gateways.rb, lib/homes_england/use_cases.rb, lib/local_authority/gateways.rb, lib/local_authority/use_case/find_path_data.rb, lib/local_authority/use_case/get_return_template_path_types.rb, lib/local_authority/use_case/populate_return_template.rb, lib/local_authority/use_cases.rb, spec/acceptance/homes_england/create_new_hif_project_spec.rb, spec/acceptance/homes_england/update_project_spec.rb, spec/acceptance/local_authority/authorise_user_with_project_spec.rb, spec/acceptance/local_authority/calculate_hif_return_spec.rb, spec/acceptance/local_authority/get_returns_spec.rb, spec/acceptance/local_authority/perform_return_spec.rb, spec/acceptance/local_authority/validate_return_spec.rb, spec/acceptance/shared_context/dependency_factory.rb, spec/unit/common/logging_spec.rb, spec/unit/local_authority/use_case/find_path_data_spec.rb, spec/unit/local_authority/use_case/populate_return_template_spec.rb
WHY
- We can't easily see what use cases are being called and with what data
WHAT
- Adds a logging proxy around our use cases to log before/after requests and responses
- Separates out use case factory to two separate containers, one for gateways and one for use cases as gateways do not implement the same interface as use cases do
- Fixed use case which did not use named arguments
=> Add logging to STDOUT

config.ru
In order to take advantage of real time logging on Heroku we need to disable the log buffering
https://devcenter.heroku.com/articles/logging
=> Disable log buffering

db/migrations/1_create_projects_table.rb, db/migrations/7_add_status_to_projects_table.rb, lib/delivery_mechanism/web_routes.rb, lib/homes_england/domain/project.rb, lib/homes_england/gateway/sequel_project.rb, lib/homes_england/use_case/find_project.rb, lib/homes_england/use_case/submit_project.rb, lib/homes_england/use_case/update_project.rb, lib/homes_england/use_cases.rb, spec/acceptance/homes_england/create_new_hif_project_spec.rb, spec/acceptance/homes_england/submit_project_spec.rb, spec/acceptance/homes_england/update_project_spec.rb, spec/unit/homes_england/gateway/sequel_project_spec.rb, spec/unit/homes_england/use_case/create_new_project_spec.rb, spec/unit/homes_england/use_case/find_project_spec.rb, spec/unit/homes_england/use_case/submit_project_spec.rb, spec/unit/homes_england/use_case/update_project_spec.rb, spec/web_routes/finding_project_spec.rb, spec/web_routes/submit_project_spec.rb
You can now have a draft or submitted status on a project to signify when it's finished being edited.
=> Create a status for projects

bin/serve.sh, db/migrations/8_baseline_integers_to_strings.rb, db/migrator.rb, lib/homes_england/builder/template/templates/hif_template.rb, lib/local_authority/gateway/in_memory_return_template.rb, spec/acceptance/local_authority/perform_return_spec.rb, spec/fixtures/base_return.json, spec/fixtures/hif_baseline.json, spec/fixtures/second_base_return.json, spec/unit/database_administrator/migration_8_spec.rb, spec/unit/local_authority/gateway/in_memory_return_template_spec.rb
**WHAT**
- Updates baseline to have strings instead of integers
- Migrates currently existing baselines
- Adds output forecast to return template
**WHY**
- Population doesn't work with integers, and there's currently no benefit to storing them as not strings
- Outputs forecast tab is required for future returns
=> Outputs forecast tab

Gemfile, Gemfile.lock, lib/delivery_mechanism/controllers/post_submit_return.rb, lib/delivery_mechanism/web_routes.rb, spec/acceptance/local_authority/notify_project_members_spec.rb, spec/simulator/notification.rb, spec/spec_helper.rb, spec/unit/local_authority/gateway/gov_email_notification_gateway_spec.rb
What - Adds an acceptance spec for sending notifications to all users as well as refactoring some related tests.  
Why - This is needed to begin adding notifications on project creation (as of this notifications are only done for returns)
=> Notify tests

lib/local_authority/gateway/in_memory_return_template.rb
This PR allows the frontend component for milestones to display instead of the horizontal component.
=> Change milestone in return template to use milestone, not horizontal

lib/delivery_mechanism/web_routes.rb, spec/web_routes/finding_project_spec.rb, spec/web_routes/get_baseline_schema_spec.rb, spec/web_routes/get_return_spec.rb, spec/web_routes/get_returns_spec.rb
Added an instruction for the find project web route telling the browser not to cache the ajax request.
This should resolve the IE issue where the app doesn't progress from the create project to project summary page correctly.
=> Add no-cache instruction in header for project find web route

lib/delivery_mechanism/web_routes.rb, lib/dependency_factory.rb, lib/ui/namespaces.rb, lib/ui/use_case/create_project.rb, lib/ui/use_case/get_project.rb, lib/ui/use_case/update_project.rb, lib/ui/use_cases.rb, spec/acceptance/ui/hif_project_spec.rb, spec/unit/ui/use_case/create_project_spec.rb, spec/unit/ui/use_case/get_project_spec.rb, spec/unit/ui/use_case/update_project_spec.rb, spec/web_routes/create_new_project_spec.rb, spec/web_routes/finding_project_spec.rb, spec/web_routes/update_project_spec.rb
WHAT 
Adds usecases in the UI namespace for all project data related usecase
WHY
To prepare to add a layer of separation between the UI representation of the data and how it's stored, we've added usecases for UI related actions which can later be extended by adding a conversion usecase
=> Add usecases for UI Project layer

bin/serve.sh, docker-compose.yml
WHAT: Moves the triggers for the additional return tags to the docker-compose file
WHY: So that the tabs can be tested locally.
=> Move environment for return tabs to docker-compose

lib/delivery_mechanism/web_routes.rb, lib/ui/use_case/convert_core_hif_project.rb, lib/ui/use_case/convert_ui_hif_project.rb, lib/ui/use_case/create_project.rb, lib/ui/use_case/get_project.rb, lib/ui/use_case/update_project.rb, lib/ui/use_cases.rb, spec/acceptance/ui/hif_project_spec.rb, spec/fixtures/hif_empty_baseline.json, spec/unit/ui/use_case/convert_core_hif_project_spec.rb, spec/unit/ui/use_case/convert_ui_hif_project_spec.rb, spec/unit/ui/use_case/create_project_spec.rb, spec/unit/ui/use_case/get_project_spec.rb, spec/unit/ui/use_case/update_project_spec.rb, spec/web_routes/update_project_spec.rb
WHAT
- Adds converts for hif projects that sit between the UI/Core layer
WHY
- To allow for easier changing of the schema for the UI without requiring DB changes
**OUTSTANDING WORK**
- Support for AC
- As this is still in heavy development I have just ignored converting AC for the moment
- Schemas for the UI layer need to be returned over the internal schemas
- as there is no difference yet this can be done in a subsequent PR
=> Add conversion methods for project related interactions

lib/local_authority/gateway/in_memory_return_template.rb, spec/fixtures/base_return.json, spec/fixtures/hif_updated_return.json, spec/fixtures/second_base_return.json
Size of the site in hectares is already filled in on the summary of the baseline.
As such, this field is now populated from that field and marked as read-only to prevent inaccurate data.
=> Populate size in hectares from the baseline and mark as readonly

lib/ui/gateway/schemas/ac_project.json
Prior to the interface between the ui and data, the fields did not require the addable tag to show the buttons on arrays.
This corrects the schema so that they work again.
=> Add the addable tag to required arrays

Makefile
The `Makefile` was missing the required `setup` target.
=> Add `setup` target to Makefile to make compliant with RFC012

lib/local_authority/gateway/sequel_return_update.rb
WHAT: Adds an order by to the map function
WHY: Postgres does not guarantee the order in which it returns data.
=> Add ordering to updates_for method on sequel_return_update

lib/local_authority/gateway/in_memory_return_template.rb, spec/acceptance/ui/hif_returns_spec.rb, spec/fixtures/base_return.json, spec/fixtures/hif_saved_base_return.json, spec/fixtures/hif_updated_return.json, spec/fixtures/second_base_return.json
WHAT:
Adds a sourceKey to the s151 Confirmation > HIF Total Funding Request field to pull data from HIF Grant Expenditure > Total HIF Grant.
WHY:
Prevent inaccurate duplication of data via human input.
=> Add sourceKey reference to hifTotalFundingRequest to prepopulate data

lib/local_authority/use_case/calculate_hif_return.rb, lib/ui/gateway/schemas/hif_return.json, lib/ui/use_case/convert_core_hif_return.rb, lib/ui/use_case/convert_ui_hif_return.rb, spec/acceptance/local_authority/calculate_hif_return_spec.rb, spec/acceptance/ui/hif_returns_spec.rb, spec/fixtures/hif_return_core.json, spec/fixtures/hif_return_ui.json, spec/fixtures/hif_return_ui_after_calcs.json, spec/fixtures/hif_saved_base_return.json, spec/unit/local_authority/use_case/calculate_hif_return_spec.rb
Added calculations for fields in S151 > Supporting Evidence > Last Quarter Month Spend to calculate the variance between forecast and actual (£ and %).
=> Calculate variance of s151 spending amounts

lib/local_authority/gateway/hif_returns_schema.rb, spec/fixtures/second_base_return.json
Update source key for lastQuarterMonthSpend to pull from the nextQuarterMonthSpend in previous return
=> Correct source key for last quarter month spend

lib/delivery_mechanism/web_routes.rb, lib/ui/gateway/schemas/ac_return.json, lib/ui/gateway/schemas/hif_return.json, lib/ui/use_cases.rb, spec/web_routes/get_return_spec.rb
Add a use case which gets the schema for the returns it lives in the UI folder and uses the UI gateway schema. perviously was pulling from local authority gateway.
=> Add ui use case to get schema for returns

lib/ui/use_case/get_base_return.rb, lib/ui/use_cases.rb, spec/unit/ui/use_case/get_base_return_spec.rb
In the UI use case for getting the base return, make sure it returns the ui return schema to the get base return end point.
=> Use ui return schema when getting the base return 

docker-compose.yml, lib/ui/gateway/schemas/hif_project.json, lib/ui/use_case/convert_core_hif_project.rb, lib/ui/use_case/convert_ui_hif_project.rb, spec/acceptance/ui/hif_validate_project_spec.rb, spec/fixtures/hif_baseline_missing_ui.json, spec/fixtures/hif_baseline_ui.json
WHAT:
Combines these three tabs under the infrastructure headings into one tab.
WHY:
Feedback from users was that there was no need for such small fields to be on different pages.
NEW:
PREVIOUS:
=> Combine Planning Status, Section 106 and Statutory Consents

lib/delivery_mechanism/controllers/post_project_to_users.rb, lib/homes_england/use_case/add_user_to_project.rb, spec/unit/homes_england/use_case/add_user_to_project_spec.rb, spec/web_routes/add_users_to_project_spec.rb
So that we can add users with roles to projects by calling the add users endpoint with:   { users: [ { email: "myemail@ahome.com, role: "A Role" }] }
=> Change the add user end point to except user roles.

.circleci/config.govpaas.yml, deploy-manifests/production-dark.yml, deploy-manifests/staging.yml, scripts/deploy.sh, scripts/flip-dark-to-live.sh
The config for CircleCI is located in `.circleci/config.govpaas.yml` and can we swapped out when ready to migrate across. This will not interfere with the current CircleCI configuration.
It's tricky to test currently as we don't have a paid account for GovPaaS, so some tweaking might be required when ready to migrate, such as memory of instances. Secrets will also need adding to CircleCI when ready, and finally the DB migrated from Heroku.
=> Add CircleCI config ready for GovPaaS migration

lib/local_authority/gateway/hif_returns_schema.rb, lib/local_authority/use_case/find_path_data.rb, lib/ui/gateway/schemas/hif_return.json, lib/ui/use_case/convert_core_hif_return.rb, lib/ui/use_case/convert_ui_hif_return.rb, spec/acceptance/ui/hif_returns_spec.rb, spec/fixtures/base_return.json, spec/fixtures/hif_return_core.json, spec/fixtures/hif_return_ui.json, spec/fixtures/hif_saved_base_return.json, spec/fixtures/hif_updated_return.json, spec/fixtures/second_base_return.json, spec/unit/local_authority/use_case/find_path_data_spec.rb, spec/unit/ui/use_case/convert_ui_hif_return_spec.rb
- changed the funding profile to quarterly components
- added a hidden profile to chose either previous profile or new profile that was requested
- extend source key so that you can decided to default to baseline if no previous return
- Use this on funding request to pull from baseline if no previous return, if not the hidden profile of previous return.
=> Extend source key so that baseline data can be chosen if there is no return data present.

lib/ui/gateway/schemas/hif_return.json
Add weeks difference calculations to:
- All planning fields
- Statutory Consents
- Land Ownership
(Land Ownership is reliant on PR https://github.com/homes-england/monitor-frontend/pull/210 to display the results)
=> Add weeks passed calculation to various infra fields

docker-compose.yml, lib/delivery_mechanism/web_routes.rb, lib/homes_england/use_case/unsubmit_project.rb, lib/homes_england/use_cases.rb, lib/local_authority/gateway/sequel_return.rb, spec/acceptance/homes_england/unsubmit_project_spec.rb
Create the ability to unsubmit and project and delete all the returns, hidden behind env variables.
Not tested as this will never go onto production, just for testing purposes.
=> Create functionality to unsubmit and delete returns

db/migrations/13_add_timestamp_to_returns.rb, lib/local_authority/domain/return.rb, lib/local_authority/gateway/sequel_return.rb, lib/local_authority/use_case/get_return.rb, lib/local_authority/use_case/get_returns.rb, lib/local_authority/use_case/submit_return.rb, spec/acceptance/local_authority/calculate_hif_return_spec.rb, spec/acceptance/local_authority/get_returns_spec.rb, spec/unit/local_authority/gateway/sequel_return_spec.rb, spec/unit/local_authority/use_case/get_returns_spec.rb, spec/unit/local_authority/use_case/submit_return_spec.rb
This PR creates a fixed timestamp upon submission and passes this to the front end for use in the returns list component.
=> Add timestamp to returns

lib/local_authority/gateway/hif_returns_schema.rb, lib/ui/gateway/schemas/hif_return.json, lib/ui/use_case/convert_core_hif_return.rb, lib/ui/use_case/convert_ui_hif_return.rb, spec/acceptance/local_authority/perform_return_spec.rb, spec/fixtures/base_return.json, spec/fixtures/hif_return_core.json, spec/fixtures/hif_return_ui.json, spec/fixtures/hif_return_ui_after_calcs.json, spec/fixtures/hif_saved_base_return_ui.json, spec/fixtures/hif_updated_return_ui.json, spec/fixtures/second_base_return.json
Add option to add housing starts and completions at the beginning of the year. 
Calculate progress percentage of actual vs forecasted
=> In year housing stats

lib/ui/gateway/schemas/hif_project.json
WHAT:
Adds N/A to the list of options available for jointBidAreas.
WHY:
Was specified that this should be marked as required, but it is a valid case that there may not be a joint bid are.
(Open to comment on whether this should have the required tag removed rather than adding an N/A option)
=> Add N/A option for jointBidAreas

lib/homes_england/use_case/add_user_to_project.rb, lib/homes_england/use_cases.rb, spec/unit/homes_england/use_case/add_user_to_project_spec.rb
When fetching the projects associated to a user it was producing an error when they had a project added to them that didnt exist.
=> Dont add a user to a project unless it exists

lib/ui/gateway/schemas/hif_return.json
As per user feedback, these fields need to be editable.
=> Remove readonly tags from completed date fields

lib/local_authority/gateway/gov_email_notification_gateway.rb
The new template includes a link to print the return.
=> Change gov notify template when submitting returns

lib/ui/gateway/schemas/ff_project.json
Part of https://github.com/homes-england/monitor-frontend/pull/291
=> Hide FF infrastructures on main project page

lib/ui/gateway/blank_projects/mvf.json, lib/ui/use_case/convert_ui_hif_project.rb
Core schema specifies that 'fundingProfiles' is an array, projects created using this blank baseline couldn't be parsed by BI
=> Correct MVF blank baseline

lib/ui/builder/template.rb, lib/ui/gateway/in_memory_project_schema.rb, lib/ui/namespaces.rb, spec/unit/ui/builder/fixtures/example_one/section_one.json, spec/unit/ui/builder/fixtures/example_one/section_two.json, spec/unit/ui/builder/fixtures/example_two/cats.json, spec/unit/ui/builder/fixtures/example_two/dogs.json, spec/unit/ui/builder/template_spec.rb
What:
- Adds a template builder to allow for building up sections of a larger more complex schema
Currently only supports adding sections in the properties -will need to be extended as we go to split up the current schemas to add additional top level items
=> Add template builder for split out schemas

lib/local_authority/use_case/check_api_key.rb, lib/local_authority/use_cases.rb, spec/acceptance/local_authority/authorise_user_with_project_spec.rb, spec/unit/local_authority/use_case/check_api_key_spec.rb
This removes the need to login every time you get added to a project, and will allow us to remove people from projects which will revoke their API key
The frontend will need to be updated to no longer delete cookies on project creation in order to take advantage of this
=> Authorise users against projects stored in the database

lib/delivery_mechanism/controllers/check_api_key.rb, spec/web_routes/check_api_key_spec.rb
This will be used by the frontend in order to ensure up to date information about the API key is used, also means we no longer need to attempt to load the entire project baseline in order to authenticate.
=> Add /apikey/check

lib/ui/gateway/schemas/ac_project.json
Currently RJSF has an issue where using minitems in our quarterly component will cause the initial items to all replicate each other when changing them
Until this is resolved it is easier to remove the minitems here as a workaround
=> Remove minitems from AC Financials

lib/ui/gateway/schemas/hif_project.json
the changing of outputs to an array was done to aid the BI work and doesnt actually reflect what happens in the internal data
to prevent us creating data that wont be saved we have unlinked these arrays
=> Unlink outputs from infrastructures array
